class_name CardData extends Node

@export var title : String
@export var description: String
@export var coords : Vector2i
@export var resource : Constants.resource
@export var when_receiving_input : Dictionary
@export var resource_vector  : Vector2i #could do something like this to handle multiple resources generated by a single tile

func _init(_title: String, _description: String, _coords: Vector2, _resource: Constants.resource, _receiving_input: Dictionary = {}):
	title = _title
	description = _description
	coords = _coords
	resource = _resource
	when_receiving_input = _receiving_input
